// Export all pages from this index file for easier imports
export { default as Home } from './Home'
export { default as MapView } from './MapView'
export { default as FacilityMap } from './FacilityMap'
export { default as MapViewTest } from './MapViewTest'
export { default as MinimalMap } from './MinimalMap'
export { default as SimpleTest } from './SimpleTest'
export { default as FacilityPopupDemo } from './FacilityPopupDemo'
export { default as AlertsSidebarDemo } from './AlertsSidebarDemo'
export { default as Dashboard } from './Dashboard'
export { default as DashboardDemo } from './DashboardDemo'
export { default as DashboardTest } from './DashboardTest'
export { default as DashboardSimple } from './DashboardSimple'
export { default as DashboardDebug } from './DashboardDebug'
export { default as DashboardNav } from './DashboardNav'

// Professional UI Components
export { default as ProfessionalHome } from './ProfessionalHome'
export { default as ProfessionalDashboard } from './ProfessionalDashboard'
export { default as ProfessionalFacilityMap } from './ProfessionalFacilityMap'
export { default as ProfessionalReports } from './ProfessionalReports'
export { default as ProfessionalMaintenance } from './ProfessionalMaintenance'